### ISSUE TITLE
Macros within conditionals

### ISSUE THREAD

**Issue by meowgorithm** [aichaos/rivescript-go#37]
Should macros execute and return before a conditional is evaluated? Currently, in a case such as this…

```
+ my name is *
* <call>isHisNameFrank <star></call> == true => Welcome, Frank.
- You’re not Frank. Go find Frank.
```

…it appears that the macro not being called at all.

[An issue in the JavaScript RiveScript project][1] makes me think the expected behavior is that macros should indeed execute before the conditional is evaluated.

[1]: https://github.com/aichaos/rivescript-js/pull/111

**Comment by kirsle** [comment]
Yeah they should work. Try turning on debug mode and see what it's doing
when it evaluates the conditionals. There might be a bug in what it's doing
with the tag that makes the condition not match correctly.

On Oct 11, 2017 6:45 PM, "Christian Rocha" <notifications@github.com> wrote:

Should macros execute and return before a conditional is evaluated?
Currently, in a case such as this…

+ my name is *
* <call>isHisNameFrank <star></call> == true => Welcome, Frank.
- You’re not Frank. Go find Frank.

…it appears that the macro not being called at all.

An issue in the JavaScript RiveScript project
<https://github.com/aichaos/rivescript-js/pull/111> makes me think the
expected behavior is that macros should indeed execute before the
conditional is evaluated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aichaos/rivescript-go/issues/37>, or mute the thread

**Comment by meowgorithm** [comment]
Gah, my mistake indeed. Verified that this works as intended.
